#################################################################################
# Eclipse Tractus-X - Software Development KIT
#
# Copyright (c) 2026 LKS NEXT
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

# Part of this content was generated by Co-Pilot and reviewed by a human developer.

"""
Schema: https://catenax-ev.github.io/docs/next/standards/CX-0149-Industry-Core
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4
import re

from pydantic import BaseModel, Field, field_validator

from ..constants import DEFAULT_HEADER_VERSION, BPN_PATTERN


# Pydantic marker indicating a field is required (more readable than bare ellipsis)
REQUIRED = ...


class NotificationHeader(BaseModel):
    """
    Notification header based on io.catenax.shared.message_header_3.0.0.
    
    This header follows the Industry Core Notifications schema structure
    as defined in the Catena-X standards.
    
    Attributes:
        message_id: Unique ID identifying the message (required)
        context: Information about the context (e.g., "IndustryCore-DigitalTwinEventAPI-ConnectToParent:2.0.0")
        sent_date_time: Timestamp when the message was sent (required)
        sender_bpn: Business Partner Number of the sender (required)
        receiver_bpn: Business Partner Number of the receiver (required)
        expected_response_by: Optional deadline for response
        related_message_id: Optional reference to a related message
        version: Header version following semantic versioning (required)
    """
    
    # Required fields from io.catenax.shared.message_header_3.0.0
    message_id: UUID = Field(
        default_factory=uuid4,
        alias="messageId",
        description="Unique ID identifying the message. The purpose of the ID is to uniquely identify a single message, therefore it MUST not be reused."
    )
    context: str = Field(
        REQUIRED,
        description="Information about the context the message should be considered in. Format: <domain>-<subdomain>-<object>:<version> (e.g., IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0)",
        examples=["IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0"]
    )
    sent_date_time: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        alias="sentDateTime",
        description="Time zone aware timestamp holding the date and time the message was sent. Formatted according to ISO 8601."
    )
    sender_bpn: str = Field(
        REQUIRED,
        alias="senderBpn",
        description="The Business Partner Number of the sending party. Must be a valid BPNL.",
        pattern=BPN_PATTERN
    )
    receiver_bpn: str = Field(
        REQUIRED,
        alias="receiverBpn",
        description="The Business Partner Number of the receiving party. Must be a valid BPNL.",
        pattern=BPN_PATTERN
    )
    version: str = Field(
        default=DEFAULT_HEADER_VERSION,
        description="The version of the message header aspect model following semantic versioning.",
        pattern=r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(\.[0-9A-Za-z-]+)*)?([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$"
    )
    
    # Optional fields from io.catenax.shared.message_header_3.0.0
    expected_response_by: Optional[datetime] = Field(
        default=None,
        alias="expectedResponseBy",
        description="Timestamp by which the sending party expects a response. Formatted according to ISO 8601."
    )
    related_message_id: Optional[UUID] = Field(
        default=None,
        alias="relatedMessageId",
        description="Unique ID identifying a message somehow related to the current one."
    )
    
    model_config = {
        "populate_by_name": True,
        "use_enum_values": True,
    }
    
    @field_validator("sender_bpn", "receiver_bpn")
    @classmethod
    def validate_bpn(cls, v: str) -> str:
        """Validate BPN format (BPNL followed by 12 alphanumeric characters)."""
        if not re.match(BPN_PATTERN, v):
            raise ValueError("BPN must match pattern BPNL followed by 12 alphanumeric characters")
        return v
    
    def to_data(self) -> Dict[str, Any]:
        """
        Convert the header to a dictionary for API requests.
        
        Returns:
            Dictionary representation with camelCase keys following the Industry Core schema
        """
        return self.model_dump(by_alias=True, exclude_none=True, mode="json")


class NotificationContent(BaseModel):
    """
    Notification content/body for Industry Core notifications.
    
    The content structure is flexible and can contain any payload.
    Common fields for quality notifications are provided as optional fields.
    
    Attributes:
        information: Human-readable description or message
        list_of_affected_items: List of affected part/serial numbers
    """
    
    information: Optional[str] = Field(
        default=None,
        description="Human-readable notification message or description"
    )
    list_of_affected_items: List[str] = Field(
        default_factory=list,
        alias="listOfAffectedItems",
        description="List of affected part or serial numbers"
    )
    
    model_config = {
        "populate_by_name": True,
        "extra": "allow",  # Allow additional fields for flexibility
    }
    
    def to_data(self) -> Dict[str, Any]:
        """
        Convert the content to a dictionary for API requests.
        
        Returns:
            Dictionary representation with camelCase keys
        """
        return self.model_dump(by_alias=True, exclude_none=True)


class Notification(BaseModel):
    """
    Complete notification model following Industry Core Notifications schema.
    
    Combines header (based on io.catenax.shared.message_header_3.0.0) and
    content into a single notification entity that can be sent through
    the Catena-X dataspace.
    
    Schema: https://catenax-ev.github.io/assets/files/notification.schema.json
    
    Attributes:
        header: Notification header with metadata (required)
        content: Notification content/body (required)
    """
    
    header: NotificationHeader = Field(
        REQUIRED,
        description="Notification header with metadata based on message_header_3.0.0"
    )
    content: NotificationContent = Field(
        default_factory=NotificationContent,
        description="Notification content/body"
    )
    
    model_config = {
        "populate_by_name": True,
    }
    
    def to_data(self) -> Dict[str, Any]:
        """
        Convert the complete notification to a dictionary for API requests.
        
        Returns:
            Dictionary representation following Industry Core Notifications schema
        """
        return {
            "header": self.header.to_data(),
            "content": self.content.to_data(),
        }
    
    def to_json_string(self) -> str:
        """
        Convert the notification to a JSON string.
        
        Returns:
            JSON string representation of the notification
        """
        return self.model_dump_json(by_alias=True, exclude_none=True)
    
    @classmethod
    def builder(cls) -> "Notification._Builder":
        """
        Create a builder instance for fluent notification construction.
        
        Returns:
            Builder instance for creating Notification objects
        """
        return cls._Builder(cls)
    
    class _Builder:
        """Builder class for fluent Notification construction following Industry Core schema."""
        
        def __init__(self, cls):
            self.cls = cls
            self._header_data: Dict[str, Any] = {}
            self._content_data: Dict[str, Any] = {}
        
        def message_id(self, message_id: UUID) -> "Notification._Builder":
            """Set the message ID (unique identifier for the message)."""
            self._header_data["message_id"] = message_id
            return self
        
        def context(self, context: str) -> "Notification._Builder":
            """Set the context (e.g., 'IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0')."""
            self._header_data["context"] = context
            return self
        
        def sent_date_time(self, sent_date_time: datetime) -> "Notification._Builder":
            """Set the sent date/time."""
            self._header_data["sent_date_time"] = sent_date_time
            return self
        
        def sender_bpn(self, sender_bpn: str) -> "Notification._Builder":
            """Set the sender BPN (BPNL format)."""
            self._header_data["sender_bpn"] = sender_bpn
            return self
        
        def receiver_bpn(self, receiver_bpn: str) -> "Notification._Builder":
            """Set the receiver BPN (BPNL format)."""
            self._header_data["receiver_bpn"] = receiver_bpn
            return self
        
        def version(self, version: str) -> "Notification._Builder":
            """Set the header version (semantic versioning)."""
            self._header_data["version"] = version
            return self
        
        def expected_response_by(self, expected_response_by: datetime) -> "Notification._Builder":
            """Set the expected response deadline."""
            self._header_data["expected_response_by"] = expected_response_by
            return self
        
        def related_message_id(self, related_message_id: UUID) -> "Notification._Builder":
            """Set a related message ID."""
            self._header_data["related_message_id"] = related_message_id
            return self
        
        def information(self, information: str) -> "Notification._Builder":
            """Set the notification message/information in content."""
            self._content_data["information"] = information
            return self
        
        def affected_items(self, items: List[str]) -> "Notification._Builder":
            """Set the list of affected items in content."""
            self._content_data["list_of_affected_items"] = items
            return self
        
        def header(self, header: NotificationHeader) -> "Notification._Builder":
            """Set the complete header."""
            self._header_data = header.model_dump()
            return self
        
        def content(self, content: NotificationContent) -> "Notification._Builder":
            """Set the complete content."""
            self._content_data = content.model_dump()
            return self
        
        def build(self) -> "Notification":
            """
            Build and return the Notification instance.
            
            Returns:
                Constructed Notification object
                
            Raises:
                ValidationError: If required fields are missing or invalid
            """
            header = NotificationHeader(**self._header_data)
            content = NotificationContent(**self._content_data)
            return self.cls(header=header, content=content)
