#################################################################################
# Eclipse Tractus-X - Software Development KIT
#
# Copyright (c) 2026 LKS NEXT
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

# Part of this content was generated by Co-Pilot and reviewed by a human developer.

import pytest
from datetime import datetime
from uuid import uuid4

from tractusx_sdk.extensions.notification_api.models import (
    NotificationHeader,
    NotificationContent,
    Notification,
)


class TestNotificationHeader:
    """Test NotificationHeader model based on io.catenax.shared.message_header_3.0.0."""
    
    @pytest.fixture
    def valid_header_data(self):
        """Fixture for valid header data following Industry Core schema."""
        return {
            "sender_bpn": "BPNL000000000001",
            "receiver_bpn": "BPNL000000000002",
            "context": "IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0",
        }
    
    def test_create_header_with_required_fields(self, valid_header_data):
        """Test creating header with only required fields."""
        header = NotificationHeader(**valid_header_data)
        
        assert header.sender_bpn == "BPNL000000000001"
        assert header.receiver_bpn == "BPNL000000000002"
        assert header.context == "IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0"
        assert header.message_id is not None
        assert header.sent_date_time is not None
        assert header.version == "3.0.0"  # Default version
    
    def test_create_header_with_all_fields(self, valid_header_data):
        """Test creating header with all fields."""
        message_id = uuid4()
        expected_response_by = datetime.now()
        related_message_id = uuid4()
        
        header = NotificationHeader(
            **valid_header_data,
            message_id=message_id,
            expected_response_by=expected_response_by,
            related_message_id=related_message_id,
        )
        
        assert header.message_id == message_id
        assert header.expected_response_by == expected_response_by
        assert header.related_message_id == related_message_id
    
    def test_header_bpn_validation_invalid_prefix(self, valid_header_data):
        """Test that BPN validation rejects invalid prefix."""
        valid_header_data["sender_bpn"] = "INVALID000000001"
        
        with pytest.raises(ValueError, match="string_pattern_mismatch"):
            NotificationHeader(**valid_header_data)
    
    def test_header_bpn_validation_invalid_length(self, valid_header_data):
        """Test that BPN validation rejects invalid length."""
        valid_header_data["sender_bpn"] = "BPNL00001"  # Too short
        
        with pytest.raises(ValueError):
            NotificationHeader(**valid_header_data)
    
    def test_header_to_data(self, valid_header_data):
        """Test header serialization with camelCase keys following Industry Core schema."""
        header = NotificationHeader(**valid_header_data)
        data = header.to_data()
        
        assert "senderBpn" in data
        assert "receiverBpn" in data
        assert "messageId" in data
        assert "context" in data
        assert "sentDateTime" in data
        assert "version" in data
        assert data["senderBpn"] == "BPNL000000000001"


class TestNotificationContent:
    """Test NotificationContent model."""
    
    def test_create_empty_content(self):
        """Test creating content with defaults."""
        content = NotificationContent()
        
        assert content.information is None
        assert content.list_of_affected_items == []
    
    def test_create_content_with_data(self):
        """Test creating content with data."""
        content = NotificationContent(
            information="Test notification message",
            list_of_affected_items=["PART001", "PART002"],
        )
        
        assert content.information == "Test notification message"
        assert content.list_of_affected_items == ["PART001", "PART002"]
    
    def test_content_to_data(self):
        """Test content serialization with camelCase keys."""
        content = NotificationContent(
            information="Test message",
            list_of_affected_items=["ITEM1"],
        )
        data = content.to_data()
        
        assert "information" in data
        assert "listOfAffectedItems" in data
        assert data["listOfAffectedItems"] == ["ITEM1"]


class TestNotification:
    """Test Notification composite model following Industry Core schema."""
    
    @pytest.fixture
    def valid_notification(self):
        """Fixture for a valid notification."""
        header = NotificationHeader(
            sender_bpn="BPNL000000000001",
            receiver_bpn="BPNL000000000002",
            context="IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0",
        )
        content = NotificationContent(
            information="Quality issue detected",
            list_of_affected_items=["SN12345", "SN67890"],
        )
        return Notification(header=header, content=content)
    
    def test_create_notification(self, valid_notification):
        """Test creating a complete notification."""
        assert valid_notification.header.sender_bpn == "BPNL000000000001"
        assert valid_notification.content.information == "Quality issue detected"
    
    def test_notification_to_data(self, valid_notification):
        """Test notification serialization."""
        data = valid_notification.to_data()
        
        assert "header" in data
        assert "content" in data
        assert data["header"]["senderBpn"] == "BPNL000000000001"
        assert data["content"]["listOfAffectedItems"] == ["SN12345", "SN67890"]
    
    def test_notification_to_json_string(self, valid_notification):
        """Test notification JSON serialization."""
        json_str = valid_notification.to_json_string()
        
        assert isinstance(json_str, str)
        assert "BPNL000000000001" in json_str
        assert "Quality issue detected" in json_str


class TestNotificationBuilder:
    """Test Notification builder pattern following Industry Core schema."""
    
    def test_builder_creates_notification(self):
        """Test creating notification using builder."""
        notification = (
            Notification.builder()
            .sender_bpn("BPNL000000000001")
            .receiver_bpn("BPNL000000000002")
            .context("IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0")
            .information("Test notification")
            .affected_items(["PART001"])
            .build()
        )
        
        assert notification.header.sender_bpn == "BPNL000000000001"
        assert notification.content.information == "Test notification"
        assert notification.content.list_of_affected_items == ["PART001"]
    
    def test_builder_with_custom_id(self):
        """Test builder with custom message ID."""
        custom_id = uuid4()
        
        notification = (
            Notification.builder()
            .message_id(custom_id)
            .sender_bpn("BPNL000000000001")
            .receiver_bpn("BPNL000000000002")
            .context("IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0")
            .build()
        )
        
        assert notification.header.message_id == custom_id
    
    def test_builder_with_related_message(self):
        """Test builder with related message reference."""
        related_id = uuid4()
        
        notification = (
            Notification.builder()
            .sender_bpn("BPNL000000000001")
            .receiver_bpn("BPNL000000000002")
            .context("IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0")
            .related_message_id(related_id)
            .build()
        )
        
        assert notification.header.related_message_id == related_id
    
    def test_builder_with_expected_response_by(self):
        """Test builder with expected response deadline."""
        deadline = datetime(2025, 12, 31, 23, 59, 59)
        
        notification = (
            Notification.builder()
            .sender_bpn("BPNL000000000001")
            .receiver_bpn("BPNL000000000002")
            .context("IndustryCore-DigitalTwinEventAPI-ConnectToParent:3.0.0")
            .expected_response_by(deadline)
            .build()
        )
        
        assert notification.header.expected_response_by == deadline
