#################################################################################
# Eclipse Tractus-X - Software Development KIT
#
# Copyright (c) 2026 LKS NEXT
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

# Part of this content was generated by Co-Pilot and reviewed by a human developer.

import pytest
from unittest.mock import Mock, MagicMock

from tractusx_sdk.extensions.notification_api.services import NotificationService
from tractusx_sdk.extensions.notification_api.exceptions import NotificationError


class TestNotificationService:
    """Test NotificationService class."""
    
    @pytest.fixture
    def service(self):
        """Fixture for notification service."""
        return NotificationService(verbose=False)
    
    def test_service_initialization(self, service):
        """Test service initialization."""
        assert service.verbose is False
        assert service.connector_provider is None


class TestNotificationServiceConnectorIntegration:
    """Test NotificationService connector integration for asset management."""
    
    @pytest.fixture
    def mock_connector_provider(self):
        """Fixture for mocked connector provider."""
        provider = Mock()
        provider.dataspace_version = "saturn"
        provider.assets = Mock()
        provider.create_asset = MagicMock()
        return provider
    
    @pytest.fixture
    def service_with_connector(self, mock_connector_provider):
        """Fixture for notification service with connector provider."""
        return NotificationService(
            connector_provider=mock_connector_provider,
            verbose=False,
        )
    
    def test_service_with_connector_provider(self, service_with_connector, mock_connector_provider):
        """Test service initialization with connector provider."""
        assert service_with_connector.connector_provider == mock_connector_provider
    
    def test_ensure_notification_asset_exists_no_provider(self):
        """Test ensure_notification_asset_exists fails without connector provider."""
        service = NotificationService(verbose=False)
        
        with pytest.raises(NotificationError, match="Connector provider is required"):
            service.ensure_notification_asset_exists(
                asset_id="test-asset",
                notification_endpoint_url="https://example.com/notifications",
            )
    
    def test_ensure_notification_asset_exists_creates_new(
        self, service_with_connector, mock_connector_provider
    ):
        """Test creating a new notification asset when it doesn't exist."""
        # Mock asset not found
        mock_response = Mock()
        mock_response.status_code = 404
        mock_connector_provider.assets.get_by_id.return_value = mock_response
        
        # Mock successful creation
        mock_connector_provider.create_asset.return_value = {
            "@id": "test-asset",
            "properties": {"dct:type": {"@id": "https://w3id.org/catenax/taxonomy#DigitalTwinEventAPI"}}
        }
        
        service_with_connector.ensure_notification_asset_exists(
            asset_id="test-asset",
            notification_endpoint_url="https://example.com/notifications",
        )
        
        mock_connector_provider.create_asset.assert_called_once()
        call_kwargs = mock_connector_provider.create_asset.call_args.kwargs
        assert call_kwargs["asset_id"] == "test-asset"
        assert call_kwargs["dct_type"] == "https://w3id.org/catenax/taxonomy#DigitalTwinEventAPI"
    
    def test_ensure_notification_asset_exists_already_exists(
        self, service_with_connector, mock_connector_provider
    ):
        """Test returning existing asset when it already exists."""
        # Mock asset found with correct type
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "@id": "test-asset",
            "properties": {"dct:type": {"@id": "https://w3id.org/catenax/taxonomy#DigitalTwinEventAPI"}}
        }
        mock_connector_provider.assets.get_by_id.return_value = mock_response
        
        result = service_with_connector.ensure_notification_asset_exists(
            asset_id="test-asset",
            notification_endpoint_url="https://example.com/notifications",
        )
        
        # Should not create a new asset
        mock_connector_provider.create_asset.assert_not_called()
        assert result["@id"] == "test-asset"
    
    def test_ensure_notification_asset_wrong_type_creates_new(
        self, service_with_connector, mock_connector_provider
    ):
        """Test creating new asset when existing asset has wrong type."""
        # Mock asset found but with wrong type
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "@id": "test-asset",
            "properties": {"dct:type": {"@id": "cx-taxo:OtherType"}}
        }
        mock_connector_provider.assets.get_by_id.return_value = mock_response
        
        # Mock successful creation
        mock_connector_provider.create_asset.return_value = {
            "@id": "test-asset-new",
            "properties": {"dct:type": {"@id": "https://w3id.org/catenax/taxonomy#DigitalTwinEventAPI"}}
        }
        
        service_with_connector.verbose = True  # Enable to test logging path
        service_with_connector.ensure_notification_asset_exists(
            asset_id="test-asset",
            notification_endpoint_url="https://example.com/notifications",
        )
        
        mock_connector_provider.create_asset.assert_called_once()


class TestNotificationServiceBuilder:
    """Test NotificationService builder pattern."""
    
    def test_builder_creates_service(self):
        """Test creating service using builder."""
        service = (
            NotificationService.builder()
            .verbose(True)
            .build()
        )
        
        assert service.verbose is True
    
    def test_builder_with_connector_provider(self):
        """Test builder with connector provider."""
        mock_provider = Mock()
        
        service = (
            NotificationService.builder()
            .connector_provider(mock_provider)
            .build()
        )
        
        assert service.connector_provider == mock_provider
