#################################################################################
# Eclipse Tractus-X - Software Development KIT
#
# Copyright (c) 2026 LKS NEXT
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

# Part of this content was generated by Co-Pilot and reviewed by a human developer.

# =============================================================================
# Asset Type Constants
# =============================================================================

# Asset type for notification endpoints following Catena-X taxonomy
# Used to identify DigitalTwinEventAPI assets in the connector catalog
# Full URL format required for catalog queries
DIGITAL_TWIN_EVENT_API_TYPE = "https://w3id.org/catenax/taxonomy#DigitalTwinEventAPI"

# Content type for notification assets
NOTIFICATION_ASSET_CONTENT_TYPE = "application/json"

# =============================================================================
# Catalog Query Constants
# =============================================================================

# DCT type filter key for catalog queries
DCT_TYPE_KEY = "'http://purl.org/dc/terms/type'.'@id'"

# =============================================================================
# Schema Version Constants
# =============================================================================

# Default message header version following io.catenax.shared.message_header_3.0.0
DEFAULT_HEADER_VERSION = "3.0.0"

# BPN pattern constant (BPNL followed by 12 alphanumeric characters)
BPN_PATTERN = r"^BPNL[a-zA-Z0-9]{12}$"

# Management API path
MANAGEMENT_API_PATH = "/management"
