#################################################################################
# Eclipse Tractus-X - Software Development KIT
#
# Copyright (c) 2026 LKS NEXT
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

# Part of this content was generated by Co-Pilot and reviewed by a human developer.

class NotificationError(Exception):
    """
    Base exception for notification-related errors.
    
    All notification-specific exceptions inherit from this class,
    allowing for broad exception catching when needed.
    """
    
    def __init__(self, message: str):
        self.message = message
        super().__init__(self.message)


class NotificationValidationError(NotificationError):
    """
    Raised when notification validation fails.
    
    This exception is raised when a notification does not meet
    the required validation criteria (e.g., missing required fields,
    invalid BPN format, etc.).
    """
    
    pass


class NotificationParsingError(NotificationError):
    """
    Raised when notification parsing fails.
    
    This exception is raised when incoming notification data
    cannot be parsed into a valid Notification model.
    """
    
    pass


class UnknownNotificationTypeError(NotificationError):
    """
    Raised when an unknown notification type is encountered.
    
    This exception is raised when a notification has an unrecognized
    classification or type that cannot be processed.
    """
    
    def __init__(self, notification_type: str):
        self.notification_type = notification_type
        super().__init__(f"Unknown notification type: {notification_type}")
